spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
  h2:
    console.enabled: true
  liquibase:
#    enabled: false
    change-log: classpath:/db/changelog/db.random-school.xml